# Generated by Django 3.2.7 on 2021-10-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='topic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
