# Generated by Django 3.2.7 on 2021-10-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0002_questions_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
