# Generated by Django 3.2.7 on 2021-10-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0003_questions_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='topic',
        ),
        migrations.AddField(
            model_name='questions',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
