# Generated by Django 3.2.7 on 2021-10-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0004_auto_20211015_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
