# Generated by Django 3.2.7 on 2021-10-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0006_alter_questions_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
