# Generated by Django 3.2.7 on 2022-01-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0007_questions_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='QGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
