# Generated by Django 3.2.7 on 2022-01-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0008_qgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
