# Generated by Django 3.2.7 on 2022-01-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0009_answers_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='answer_text',
            new_name='description',
        ),
    ]
