# Generated by Django 3.2.7 on 2022-01-27 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questans', '0010_rename_answer_text_answers_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='description',
            new_name='answer',
        ),
    ]
